version: "3"
services:
    apibar:
        restart: unless-stopped
        build:
          context: .
        environment:
            - ConnectionStrings:Bar.API=Server=db,1433;Database=bardb;User=sa;Password=MasterIsGoodPw24;
        ports:
            - "82:80"
        depends_on:
            - db
        links:
            - db
        networks:
            - mynet
    db:
        restart: unless-stopped
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment:
            SA_PASSWORD: "MasterIsGoodPw24"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - 1403:1433
        networks:
            - mynet
networks:
  mynet:
    driver: bridge